[package]
name = "project_bindings"
version = "0.1.0"
authors = ["Sven Linden <sven.linden@ilt.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
project = { path = "../project" }
